### ISSUE TITLE
ROR Group Project Kanban Board Setup

### ISSUE THREAD

**Issue by MNisarAli** [MNisarAli/recipe_app#10]
## Hi 👋 there!
- In this capstone project we are a team of two people and have divided our projects equally among ourselves.

  - **Team member - 1**: @anita00001
  - **Team member - 2**: @MNisarAli
### Thank you so much for your precious time in reviewing our project. 🙏

**Comment by DammyShittu** [comment]
Hi @anita00001 and @MNisarAli,

## APPROVED 🟢

## Highlights
✔️ Descriptive tasks

Great implementation of all the requirements in this milestone. 👏 

_You have done an amazing job 👍_

Your project is complete!  There is nothing else to say other than... it's time to merge it. :shipit: 

Congratulations! 🎉 

## CHEERS AND HAPPY CODING!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
